networks:
  perkup-net:
    external: true

volumes:
  portainer_data:
    driver: local

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - PORTAINER_HTTP_DISABLED=false
      - PORTAINER_TRUSTED_ORIGINS=portainer.digitalmoontech.com.br
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - perkup-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.digitalmoontech.com.br`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # Adiciona headers corretos
      - "traefik.http.routers.portainer.middlewares=portainer-headers"
      - "traefik.http.middlewares.portainer-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.portainer-headers.headers.customrequestheaders.X-Forwarded-Host=portainer.digitalmoontech.com.br"
    depends_on:
      - traefik
  
  traefik:
    image: traefik:v3.2
    container_name: soiltraefik
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - perkup-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml