networks:
  perkup-net:
    external: true

volumes:
  portainer_data:
    driver: local
  traefik_logs:
    driver: local
  traefik_grafana_data:
    driver: local

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - PORTAINER_HTTP_DISABLED=false
      - PORTAINER_TRUSTED_ORIGINS=cloud.nikoliveira.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - perkup-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`cloud.nikoliveira.com`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
    depends_on:
      - traefik
  
  traefik:
    image: traefik:v3.2
    container_name: soiltraefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - perkup-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - traefik_logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.nikoliveira.com`)"
      - "traefik.http.routers.api.service=api@internal"

  # Jaeger para tracing distribuído
  traefik-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: traefik-jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - perkup-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-jaeger.rule=Host(`jaeger.nikoliveira.com`)"
      - "traefik.http.services.traefik-jaeger.loadbalancer.server.port=16686"

  # Prometheus para métricas
  traefik-prometheus:
    image: prom/prometheus:latest
    container_name: traefik-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - perkup-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-prometheus.rule=Host(`prometheus.nikoliveira.com`)"
      - "traefik.http.services.traefik-prometheus.loadbalancer.server.port=9090"

  # Grafana para visualização
  traefik-grafana:
    image: grafana/grafana:latest
    container_name: traefik-grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - traefik_grafana_data:/var/lib/grafana
    networks:
      - perkup-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-grafana.rule=Host(`grafana.nikoliveira.com`)"
      - "traefik.http.services.traefik-grafana.loadbalancer.server.port=3000"