global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Configuração para coletar métricas do Traefik
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  # Configuração para coletar métricas do Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Configuração para aplicação Laravel (se expuser métricas)
  - job_name: 'laravel-app'
    static_configs:
      - targets: ['perkup-laravel:3000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
