api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# Configuração avançada de logs
log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

# Logs de acesso mais detalhados
accessLog:
  format: json
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "200"
      - "300-302"
      - "400-499"
      - "500-599"
    retryAttempts: true
    minDuration: "10ms"
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: drop
        Content-Type: keep

# Configuração de métricas
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    entryPoint: traefik

# Configuração de tracing
tracing:
  jaeger:
    samplingServerURL: http://traefik-jaeger:14268/api/sampling
    samplingType: const
    samplingParam: 1.0
    localAgentHostPort: traefik-jaeger:6831
    gen128Bit: true
    propagation: jaeger
    traceContextHeaderName: uber-trace-id